/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-24 23:50:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import user.member.model.service.UserService;
import user.member.controller.*;
import user.vo.User;

public final class Analysis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1598309248856L));
    _jspx_dependants.put("/WEB-INF/views/common/userHeader.jsp", Long.valueOf(1598309660973L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("user.member.controller");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("user.vo.User");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("user.member.model.service.UserService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

	User memberLoggedIn = (User)session.getAttribute("memberLoggedIn");
    String adminGrade = UserService.USER_ADMIN;

	//쿠키확인 : 요청과 함께 전송된 쿠키확인
	boolean saveId = false;
	String userId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null){
		for(Cookie c : cookies){
			String key = c.getName();
			String value = c.getValue();
			if("saveId".equals(key)){
				saveId = true;
				userId = value;
			}
		}
	}	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write(" <script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("\t$(\"#user-login-form\").submit(function(){\r\n");
      out.write("\t\tvar $userId = $(\"#input-login-id\");\r\n");
      out.write("\t\tvar $password = $(\"#input-login-password\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(/^.{4,}$/.test($userId.val()) == false){\r\n");
      out.write("\t\t\talert(\"유효한 아이디를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\tif(/^.{4,}$/.test($password.val()) == false){\r\n");
      out.write("\t\t\talert(\"유효한 패스워드를 입력하세요.\");\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t        });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // 로그인 드롭다운 \r\n");
      out.write("        function mypage(){\r\n");
      out.write("            $(\"#mypage-login\").slideToggle();    \r\n");
      out.write("            $(\"#mypage-loggedIn\").slideToggle();    \r\n");
      out.write("        }\r\n");
      out.write("        // 비밀번호 변경 시 js 효과\r\n");
      out.write("/*         function lostPw(){\r\n");
      out.write("            $(\"#mypage-login\").slideUp();\r\n");
      out.write("            $(\"#mypage-lostpw\").slideDown('300', 'linear');\r\n");
      out.write("        }; */\r\n");
      out.write("        // 비밀번호 변경 시 정보 체크\r\n");
      out.write("        function infoChk(){\r\n");
      out.write("            var INFO = 1;\r\n");
      out.write("            if(INFO = 1){\r\n");
      out.write("                alert(\"비밀번호 변경이 완료되었습니다!\");\r\n");
      out.write("                 $(\"#mypage-lostpw\").slideUp();\r\n");
      out.write("                $(\"#mypage-lostpw\").css(\"display\", \"none.\");\r\n");
      out.write("                $(\"#mypage-login\").slideDown(); \r\n");
      out.write("\r\n");
      out.write("            }else{\r\n");
      out.write("                alert(\"입력하신 정보가 고객님의 회원 정보와 일치하지 않습니다.\\n다시 확인해 주세요.\");\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        $(function(){\r\n");
      out.write("        \t$(\"#logout\").click(function(){\r\n");
      out.write("        \t\t$(\"#mypage-login\").slideToggle();\r\n");
      out.write("        \t\t$(\"#mypage-loggedIn\").slideToggle();\r\n");
      out.write("        \t\tvar result = confirm(\"로그아웃 하시겠습니까?\");\r\n");
      out.write("            \tif(result){\r\n");
      out.write("            \t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/user/logout\";\r\n");
      out.write("            \t\talert(\"성공적으로 로그아웃 되었습니다!\");\r\n");
      out.write("            \t}\r\n");
      out.write("        \t});\r\n");
      out.write("        });\r\n");
      out.write("        function adminLogout(){\r\n");
      out.write("        \tvar result = confirm(\"로그아웃 하시겠습니까?\");\r\n");
      out.write("        \tif(result){\r\n");
      out.write("        \t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/user/logout\";\r\n");
      out.write("        \t\talert(\"성공적으로 로그아웃 되었습니다!\");\r\n");
      out.write("        \t}\r\n");
      out.write("        };\r\n");
      out.write("        //비밀번호 재설정\r\n");
      out.write("        function lostPw(){\r\n");
      out.write("        \tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/user/checkInfo\";\r\n");
      out.write("        \t\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        //리뷰팝업\r\n");
      out.write("\t        function writeReview(){\r\n");
      out.write("        \tvar url = \"");
      out.print(request.getContextPath());
      out.write("/user/writeReview\";\r\n");
      out.write("        \tvar title = \"WriteReviewPopup\";\r\n");
      out.write("        \tvar status = \"left=366px, top=100px, width=700px, height=450px\";\r\n");
      out.write("        \t\r\n");
      out.write("        \topen(url, title, status);\r\n");
      out.write("        }; \r\n");
      out.write("        \r\n");
      out.write("        function msg(){\r\n");
      out.write("        \tvar url = \"");
      out.print( request.getContextPath() );
      out.write("/user/message?userId=");
      out.print( memberLoggedIn != null ? memberLoggedIn.getUserId() : "" );
      out.write("\";\r\n");
      out.write("        \tvar title = \"My Message\";\r\n");
      out.write("        \tvar status = \"left= 366px, top=100px, width=700px, height=450;\";\r\n");
      out.write("        \topen(url, title, status);\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("    <style>\r\n");
      out.write("\t  @font-face {\r\n");
      out.write("        font-family: 'IBMPlexSansKR-Regular';\r\n");
      out.write("        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/IBMPlexSansKR-Regular.woff') format('woff');\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("        }  \r\n");
      out.write("        html, body{\r\n");
      out.write("        font-family: 'IBMPlexSansKR-Regular';\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 회원이 현재 로그인하지 않은 경우, 즉 비회원인 경우 -->\r\n");
 if (memberLoggedIn == null){ 
      out.write("\t\r\n");
      out.write("    <div class=\"wrapper-user-header\">\r\n");
      out.write("        <div class=\"user-header\">\r\n");
      out.write("            <div class=\"user-navbar\">\r\n");
      out.write("                    <div class=\"navbar-user-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath());
      out.write("\"><button id=\"logo-btn\" class=\"logo-btn\">cooking-king</button></a>\r\n");
      out.write("            <button class=\"user-navbar1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/list'\">클래스</button>\r\n");
      out.write("            <button class=\"user-navbar2\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/schedule'\">내 스케줄</button>\r\n");
      out.write("            <button class=\"user-navbar4\" id=\"mypage-btn\" onclick=\"mypage();\">로그인</button>\r\n");
      out.write("            <button class=\"user-navbar5\" onclick=\"\">고객센터</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       <div class=\"login-wrapper\">\r\n");
      out.write("            <div class=\"mypage-login\" id=\"mypage-login\">\r\n");
      out.write("                <p id=\"welcome-back\" class=\"welcome-back\">WELCOME!</p>\r\n");
      out.write("                <form class=\"user-login-form\" id=\"user-login-form\"\r\n");
      out.write("                action=\"");
      out.print( request.getContextPath() );
      out.write("/user/login\"\r\n");
      out.write("\t\t\t\t\t  method=\"POST\">\r\n");
      out.write("                    <input type=\"text\" class=\"input-login-id\" id=\"input-login-id\" name=\"userId\"\r\n");
      out.write("                        placeholder=\"아이디를 입력하세요.\" value=\"");
      out.print( saveId ? userId : "");
      out.write("\" required><br>\r\n");
      out.write("                    <input type=\"password\" class=\"input-login-password\" id=\"input-login-password\" name=\"password\"\r\n");
      out.write("                        placeholder=\"비밀번호를 입력하세요.\" required><br>\r\n");
      out.write("                        <a href=\"#\" id=\"lost-pw\" class=\"lost-pw-question\" onclick=\"lostPw();\">비밀번호를 잊으셨나요?</a>\r\n");
      out.write("                        <br />\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath());
      out.write("/user/enroll\" \r\n");
      out.write("                        id=\"register-q\" class=\"register-question\">또는 회원가입을 원하시나요?</a>\r\n");
      out.write("                        <br />\r\n");
      out.write("                    <input type=\"submit\" value=\"로그인\" id=\"login-btn\" class=\"login-btn\" onclick=\"login();\" required><br>\r\n");
      out.write("                </form>\r\n");
      out.write("           </div>\r\n");
      out.write("     </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 여기까지 확인 완료 -->\r\n");
      out.write("  ");
 } else if (memberLoggedIn != null && !memberLoggedIn.getCommGrade().equals(adminGrade)){ 
      out.write("\r\n");
      out.write("      <div class=\"wrapper-user-header\">\r\n");
      out.write("        <div class=\"user-header\">\r\n");
      out.write("            <div class=\"user-navbar\">\r\n");
      out.write("                    <div class=\"navbar-user-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath());
      out.write("\"><button id=\"logo-btn\" class=\"logo-btn\">cooking-king</button></a>\r\n");
      out.write("            <button class=\"user-navbar1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/list'\">클래스</button>\r\n");
      out.write("            <button class=\"user-navbar2\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/schedule?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("'\">내 스케줄</button>\r\n");
      out.write("            <button class=\"user-navbar4\" id=\"mypage-btn\" onclick=\"mypage();\">마이페이지</button>\r\n");
      out.write("            <button class=\"user-navbar5\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/center/list'\">고객센터</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("      <div class=\"mypage-loggedIn\" id=\"mypage-loggedIn\">\r\n");
      out.write("   \t\t<div class=\"hello\" id=\"hello\">\r\n");
      out.write("   \t\t\t<p class=\"hello-p\">");
      out.print( memberLoggedIn.getUserName() );
      out.write("님, 안녕하세요.</p>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("        <div class=\"mypage\" id=\"mypage\">\r\n");
      out.write("            <button class=\"mypages\" id=\"myinfo\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/user/view?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("'\">내 정보 수정</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"point-charge\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/point/pointManagement'\">포인트 관리</button><br />\r\n");
      out.write("           <button class=\"mypages\" id=\"write-resume\" onclick=\"");
      out.print("P".equals(memberLoggedIn.getResumeYNP()) ? "alert('이력서심사가 진행중입니다.')" : "location.href='" +request.getContextPath()+ "/tutor/writerResume?userId=" +memberLoggedIn.getUserId()+"'" );
      out.write("\">이력서 관리</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"write-review\" onclick=\"writeReview();\">리뷰 작성</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"get-msg\" onclick=\"msg();\">메세지</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"logout\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\">로그아웃</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>    \r\n");
      out.write("        ");
 } else if (memberLoggedIn != null && memberLoggedIn.getCommGrade().equals(adminGrade)){ 
      out.write("\r\n");
      out.write("    \t    <div class=\"wrapper-admin-header\">\r\n");
      out.write("       \t\t\t <div class=\"admin-header\">\r\n");
      out.write("          \t\t\t  <div class=\"admin-navbar\">\r\n");
      out.write("                    <div class=\"navbar-admin-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath());
      out.write("\"><button id=\"logo-btn-a\">cooking-king</button></a>\r\n");
      out.write("            <button class=\"admin-navbar0\" id=\"admin-logout\" onclick=\"adminLogout();\">로그아웃</button>\r\n");
      out.write("            <button class=\"admin-navbar1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/list'\">클래스 관리</button>\r\n");
      out.write("            <button class=\"admin-navbar2\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/page'\">회원 관리</button>\r\n");
      out.write("            <button class=\"admin-navbar4\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/admin/analysis'\">현황 조회</button>\r\n");
      out.write("            <button class=\"admin-navbar5\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/center/list'\">고객센터</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       \t\t\t <div class=\"helloAdmin\" id=\"helloAdmin\">\r\n");
      out.write("   \t\t\t\t\t<p class=\"helloAdmin-p\" onclick=\"adminLogout();\">\r\n");
      out.write("   \t\t\t\t\t");
      out.print( memberLoggedIn.getUserName() );
      out.write("님, 안녕하세요. </p>\r\n");
      out.write("   \t\t\t\t </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \t");
 } 
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
 
List<Integer> list = (List<Integer>)request.getAttribute("list"); 
List<String> pAmount = (List<String>)request.getAttribute("pAmount");
List<Integer> pCnt = (List<Integer>)request.getAttribute("pCnt");
/*  주: 	주간 데이터의 경우 DecimalFormat 적용하여 String 형태로 리턴된다.
		이 아래부터 받아오는 리스트 데이터들은 js의 chart.js 캔버스에 대입될 주간 데이터이며, 
		6일 전 데이터 ~ 당일 데이터가 index[0]~[6]에 분포되어 있다. @yb */
List<Integer> rW = (List<Integer>)request.getAttribute("rWeekly");
List<Integer> mWT = (List<Integer>)request.getAttribute("mWeeklyT");
List<Integer> mWU = (List<Integer>)request.getAttribute("mWeeklyU");

SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일 ");
Date date = new Date();
sdf.format(date);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/analysis.css\" />\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"analy-outer\">\r\n");
      out.write("<div class=\"analysis-wrapper\">\r\n");
      out.write("<div class=\"index-bg\">\r\n");
      out.write("\r\n");
      out.write("<!-- 여기서부터 매출 현황 -->\r\n");
      out.write("<div class=\"a2-outer-wrapper\">\r\n");
      out.write("  <div class=\"analy2-wrapper\">\r\n");
      out.write("  <div class=\"card2\">\r\n");
      out.write("      <!-- Custom information -->\r\n");
      out.write("      <div class=\"about2\">\r\n");
      out.write("        <h3>매출 현황</h3>\r\n");
      out.write("        <p class=\"lead2\">최근 7일간 발생한 매출 현황입니다.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Canvas for Chart.js -->\r\n");
      out.write("      <canvas id=\"canvas2\"></canvas>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Custom Axis -->\r\n");
      out.write("      <div class=\"axis2\">\r\n");
      out.write("        <div class=\"tick2\">\r\n");
      out.write("          <span class=\"day-name2\">6일 전</span>\r\n");
      out.write("          <span class=\"value2 value--this2\">");
      out.print( rW.get(2)/10000 );
      out.write("만원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tick2\">\r\n");
      out.write("          <span class=\"day-name2\">5일 전</span>\r\n");
      out.write("          <span class=\"value2 value--this2\">");
      out.print( rW.get(3)/10000 );
      out.write("만원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tick2\">\r\n");
      out.write("          <span class=\"day-name2\">4일 전</span>\r\n");
      out.write("          <span class=\"value2 value--this2\">");
      out.print( rW.get(4)/10000 );
      out.write("만원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tick2\">\r\n");
      out.write("          <span class=\"day-name2\">3일 전</span>\r\n");
      out.write("          <span class=\"value2 value--this2\">");
      out.print( rW.get(5)/10000 );
      out.write("만원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tick2\">\r\n");
      out.write("          <span class=\"day-name2\">2일 전</span>\r\n");
      out.write("          <span class=\"value2 value--this2\">");
      out.print( rW.get(6)/10000 );
      out.write("만원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tick2\">\r\n");
      out.write("          <span class=\"day-name2\">1일 전</span>\r\n");
      out.write("          <span class=\"value2 value--this2\">");
      out.print( rW.get(7)/10000 );
      out.write("만원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tick2\">\r\n");
      out.write("          <span class=\"day-name2\">오늘</span>\r\n");
      out.write("          <span class=\"value2 value--this2\">");
      out.print( rW.get(8)/10000 );
      out.write("만원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"anal2-cont-wrapper\">\r\n");
      out.write("  <div class=\"analy2-cont2\">\r\n");
      out.write("    <p>");
      out.print( sdf.format(date));
      out.write(" 기준,</p>\r\n");
      out.write("    총 매출은 <strong>");
      out.print( pAmount.get(0) );
      out.write("</strong>이며<br>\r\n");
      out.write("    그 중 충전 수익은\r\n");
      out.write("    <strong>");
      out.print( pAmount.get(1) );
      out.write("</strong>,<br>\r\n");
      out.write("    환전 수익은 <strong>");
      out.print( pAmount.get(2) );
      out.write("</strong>입니다.<br>\r\n");
      out.write("    총 포인트 입출 건수는 <strong>");
      out.print( pCnt.get(0) );
      out.write("번</strong>,<br>\r\n");
      out.write("    그 중 입금 횟수는 <strong>");
      out.print( pCnt.get(1) );
      out.write("번</strong>,<br>\r\n");
      out.write("    출금 횟수는 <strong>");
      out.print( pCnt.get(2) );
      out.write("번</strong>입니다.\r\n");
      out.write("    <div class=\"go-point-wrapper\">\r\n");
      out.write("    <button class=\"go-point\">포인트 관리 화면으로 이동</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("                <!-- 여기까지 매출 현황 -->\r\n");
      out.write("\r\n");
      out.write("      <!-- 여기서부터 멤버 현황 -->\r\n");
      out.write("    <div class=\"a1-outer-wrapper\">\r\n");
      out.write("    <div class=\"analy1-wrapper\">\r\n");
      out.write("    <div class=\"card1\">\r\n");
      out.write("        <!-- Custom information -->\r\n");
      out.write("        <div class=\"about1\">\r\n");
      out.write("          <h3>모든 신규 회원</h3>\r\n");
      out.write("          <p class=\"lead1\">최근 7일간 신규 가입한 회원의 수입니다.</p>\r\n");
      out.write("          <div class=\"legends1\">\r\n");
      out.write("            <div class=\"info1\">\r\n");
      out.write("              <span class=\"legend1 legend--this1\"></span>\r\n");
      out.write("              <p class=\"legend--this-p\">튜터</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info1\">\r\n");
      out.write("              <span class=\"legend1 legend--prev1\"></span>\r\n");
      out.write("              <p class=\"legend--prev-p1\">유저</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Canvas for Chart.js -->\r\n");
      out.write("        <canvas id=\"canvas1\"></canvas>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Custom Axis -->\r\n");
      out.write("        <div class=\"axis1\">\r\n");
      out.write("          <div class=\"tick1\">\r\n");
      out.write("              <!-- 여기에도 마찬가지로 request.getParameter()로 각 값을 대입할 것. -->\r\n");
      out.write("            6일 전\r\n");
      out.write("            <span class=\"value1 value--this1\">");
      out.print( mWT.get(0) );
      out.write("명</span>\r\n");
      out.write("            <span class=\"value1 value--prev1\">");
      out.print( mWU.get(0) );
      out.write("명</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tick1\">\r\n");
      out.write("            5일 전\r\n");
      out.write("            <span class=\"value1 value--this1\">");
      out.print( mWT.get(1) );
      out.write("명</span>\r\n");
      out.write("            <span class=\"value1 value--prev1\">");
      out.print( mWU.get(1) );
      out.write("명</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tick1\">\r\n");
      out.write("            4일 전\r\n");
      out.write("            <span class=\"value1 value--this1\">");
      out.print( mWT.get(2) );
      out.write("명</span>\r\n");
      out.write("            <span class=\"value1 value--prev1\">");
      out.print( mWU.get(2) );
      out.write("명</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tick1\">\r\n");
      out.write("            3일 전\r\n");
      out.write("            <span class=\"value1 value--this1\">");
      out.print( mWT.get(3) );
      out.write("명</span>\r\n");
      out.write("            <span class=\"value1 value--prev1\">");
      out.print( mWU.get(3) );
      out.write("명</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tick1\">\r\n");
      out.write("            2일 전\r\n");
      out.write("            <span class=\"value1 value--this1\">");
      out.print( mWT.get(4) );
      out.write("명</span>\r\n");
      out.write("            <span class=\"value1 value--prev1\">");
      out.print( mWU.get(4) );
      out.write("명</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tick1\">\r\n");
      out.write("            1일 전\r\n");
      out.write("            <span class=\"value1 value--this1\">");
      out.print( mWT.get(5) );
      out.write("명</span>\r\n");
      out.write("            <span class=\"value1 value--prev1\">");
      out.print( mWU.get(5) );
      out.write("명</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tick1\">\r\n");
      out.write("            \t오늘\r\n");
      out.write("            <span class=\"value1 value--this1\">");
      out.print( mWT.get(6) );
      out.write("명</span>\r\n");
      out.write("            <span class=\"value1 value--prev1\">");
      out.print( mWU.get(6) );
      out.write("명</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<!-- 여기까지 차트 디자인 -->\r\n");
      out.write("\r\n");
      out.write("      <!-- 여기서부터 본문 영역 -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"anal1-cont-wrapper\">\r\n");
      out.write("      <div class=\"analy1-cont1\">\r\n");
      out.write("        <div class=\"go-mm-wrapper\">\r\n");
      out.write("        <button class=\"go-mm\">회원 관리 화면으로 이동</button>\r\n");
      out.write("      </div>\r\n");
      out.write("        <p>");
      out.print( sdf.format(date));
      out.write(" 기준,</p>\r\n");
      out.write("        전체 회원은 <strong>");
      out.print( list.get(0) );
      out.write("명</strong>이며<br>\r\n");
      out.write("        그 중 현재 활동 중인 회원은 \r\n");
      out.write("        <strong>");
      out.print( list.get(0) - list.get(1) );
      out.write("명</strong>,<br>\r\n");
      out.write("        사이트를 탈퇴한 회원은 <strong>");
      out.print( list.get(1) );
      out.write("명</strong>입니다.<br>\r\n");
      out.write("        활동 중인 회원 중 일반 유저는 \r\n");
      out.write("        <strong>");
      out.print( list.get(3) );
      out.write("명</strong>,<br>\r\n");
      out.write("        튜터 회원은 <strong>");
      out.print( list.get(2) );
      out.write("명</strong>입니다.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <!-- 여기까지 멤버 현황 -->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.8.0\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("        // 여기서부터 매출 현황\r\n");
      out.write("\r\n");
      out.write("        var canvas2 = document.getElementById(\"canvas2\");\r\n");
      out.write("\r\n");
      out.write("// Apply multiply blend when drawing datasets\r\n");
      out.write("var multiply2 = {\r\n");
      out.write("  beforeDatasetsDraw: function(chart, options, el) {\r\n");
      out.write("    chart.ctx.globalCompositeOperation = 'multiply';\r\n");
      out.write("  },\r\n");
      out.write("  afterDatasetsDraw: function(chart, options) {\r\n");
      out.write("    chart.ctx.globalCompositeOperation = 'source-over';\r\n");
      out.write("  },\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var config2 = {\r\n");
      out.write("    type: 'line',\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: [\"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\"],\r\n");
      out.write("        datasets: [\r\n");
      out.write("          {\r\n");
      out.write("              label: '',\r\n");
      out.write("              data: [");
      out.print( rW.get(1));
      out.write(',');
      out.write(' ');
      out.print( rW.get(2));
      out.write(',');
      out.write(' ');
      out.print( rW.get(3));
      out.write(", \r\n");
      out.write("            \t  ");
      out.print( rW.get(4));
      out.write(',');
      out.write(' ');
      out.print( rW.get(5));
      out.write(',');
      out.write(' ');
      out.print( rW.get(6));
      out.write(',');
      out.print( rW.get(7));
      out.write(',');
      out.write(' ');
      out.print( rW.get(8));
      out.write("],\r\n");
      out.write("              fill: false,\r\n");
      out.write("              borderColor: 'rgba(255, 255, 255, 0.2)',\r\n");
      out.write("              borderWidth: 2,\r\n");
      out.write("              pointBackgroundColor: 'transparent',\r\n");
      out.write("              pointBorderColor: '#FFFFFF',\r\n");
      out.write("              pointBorderWidth: 3,\r\n");
      out.write("              pointHoverBorderColor: 'rgba(255, 255, 255, 0.2)',\r\n");
      out.write("              pointHoverBorderWidth: 10,\r\n");
      out.write("              lineTension: 0,\r\n");
      out.write("          }\r\n");
      out.write("        ]\r\n");
      out.write("    },\r\n");
      out.write("    options: {\r\n");
      out.write("    \tresponsive: false,\r\n");
      out.write("      elements: { \r\n");
      out.write("        point: {\r\n");
      out.write("          radius: 7,\r\n");
      out.write("          hitRadius: 7, \r\n");
      out.write("          hoverRadius: 7 \r\n");
      out.write("        } \r\n");
      out.write("      },\r\n");
      out.write("      legend: {\r\n");
      out.write("        display: false,\r\n");
      out.write("      },\r\n");
      out.write("      tooltips: {\r\n");
      out.write("      \tbackgroundColor: 'sales',\r\n");
      out.write("        displayColors: false,\r\n");
      out.write("        bodyFontSize: 12,\r\n");
      out.write("        callbacks: {\r\n");
      out.write("          label: function(tooltipItems, data) { \r\n");
      out.write("            return tooltipItems.yLabel+\"원\";\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      },\r\n");
      out.write("      scales: {\r\n");
      out.write("        xAxes: [{\r\n");
      out.write("          display: false,\r\n");
      out.write("        }],\r\n");
      out.write("        yAxes: [{\r\n");
      out.write("          display: false,\r\n");
      out.write("          ticks: {\r\n");
      out.write("            beginAtZero: true,\r\n");
      out.write("          },\r\n");
      out.write("        }]\r\n");
      out.write("      }\r\n");
      out.write("    },\r\n");
      out.write("    plugins: [multiply2],\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("window.chart = new Chart(canvas2, config2);\r\n");
      out.write("\r\n");
      out.write("// 여기까지 매출 현황\r\n");
      out.write("\r\n");
      out.write("// 여기서부터 멤버 현황\r\n");
      out.write("var canvas1 = document.getElementById(\"canvas1\");\r\n");
      out.write("\r\n");
      out.write("// Apply multiply blend when drawing datasets\r\n");
      out.write("var multiply1 = {\r\n");
      out.write("  beforeDatasetsDraw: function(chart1, options, el) {\r\n");
      out.write("    chart.ctx.globalCompositeOperation = 'multiply';\r\n");
      out.write("  },\r\n");
      out.write("  afterDatasetsDraw: function(chart1, options) {\r\n");
      out.write("    chart.ctx.globalCompositeOperation = 'source-over';\r\n");
      out.write("  },\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("// 이 곳에 대입되는 색의 값은 순서대로 --this와 --prev에 대입된 값과 일치해야 함.\r\n");
      out.write("// 전위에 선언된 값이 상단의 색, 후위에 선언된 색이 하단의 색으로 gradient 적용됨.\r\n");
      out.write("// 주. 너무 어두운 색을 선택하는 경우 중첩된 색이 예쁘게 나오지 않으므로 alpha 값을 대입하거나\r\n");
      out.write("// 명도가 높은 색상을 선택할 것.\r\n");
      out.write("var gradT = canvas1.getContext('2d').createLinearGradient(0, 0, 0, 150);\r\n");
      out.write("gradT.addColorStop(0, 'rgba(6, 158, 6, 0.8)');\r\n");
      out.write("gradT.addColorStop(1, 'rgba(165, 151, 253, 0.453)');\r\n");
      out.write("\r\n");
      out.write("var gradU = canvas1.getContext('2d').createLinearGradient(0, 0, 0, 150);\r\n");
      out.write("gradU.addColorStop(0, '#FF8787');\r\n");
      out.write("gradU.addColorStop(1, 'rgba(236, 140, 255, 0.8)');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var config1 = {\r\n");
      out.write("    type: 'line',\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: [\"\", \"\", \"\", \"\", \"\", \"\", \"\"],\r\n");
      out.write("        datasets: [\r\n");
      out.write("          {\r\n");
      out.write("              label: 'tutors',\r\n");
      out.write("              data: [");
      out.print( mWT.get(0));
      out.write(',');
      out.write(' ');
      out.print( mWT.get(1));
      out.write(',');
      out.write(' ');
      out.print( mWT.get(2));
      out.write(',');
      out.write(' ');
      out.print( mWT.get(3));
      out.write(", \r\n");
      out.write("              ");
      out.print( mWT.get(4));
      out.write(',');
      out.write(' ');
      out.print( mWT.get(5));
      out.write(',');
      out.write(' ');
      out.print( mWT.get(6));
      out.write("],\r\n");
      out.write("              backgroundColor: gradT,\r\n");
      out.write("              borderColor: 'transparent',\r\n");
      out.write("              pointBackgroundColor: '#FFFFFF',\r\n");
      out.write("              pointBorderColor: '#FFFFFF',\r\n");
      out.write("              lineTension: 0.40,\r\n");
      out.write("          },\r\n");
      out.write("          {\r\n");
      out.write("              label: 'users',\r\n");
      out.write("            // 값에 변화를 주면 그래프도 함께 따라옴. \r\n");
      out.write("            // data array 내부에 도입할 각 값들(int)은 request.getParameter로 불러온 후 대입할 것.\r\n");
      out.write("              data: [");
      out.print( mWU.get(0));
      out.write(',');
      out.write(' ');
      out.print( mWU.get(1));
      out.write(',');
      out.write(' ');
      out.print( mWU.get(2));
      out.write(',');
      out.write(' ');
      out.print( mWU.get(3));
      out.write(", \r\n");
      out.write("            \t  ");
      out.print( mWU.get(4));
      out.write(',');
      out.write(' ');
      out.print( mWU.get(5));
      out.write(',');
      out.write(' ');
      out.print( mWU.get(6));
      out.write("],\r\n");
      out.write("              backgroundColor: gradU,\r\n");
      out.write("              borderColor: 'transparent',\r\n");
      out.write("              pointBackgroundColor: '#FFFFFF',\r\n");
      out.write("              pointBorderColor: '#FFFFFF',\r\n");
      out.write("              lineTension: 0.40,\r\n");
      out.write("          }\r\n");
      out.write("        ]\r\n");
      out.write("    },\r\n");
      out.write("    options: {\r\n");
      out.write("    \t\telements: { \r\n");
      out.write("        \tpoint: {\r\n");
      out.write("          \tradius: 0,\r\n");
      out.write("          \thitRadius: 5, \r\n");
      out.write("            hoverRadius: 5 \r\n");
      out.write("          } \r\n");
      out.write("        },\r\n");
      out.write("    \t\tlegend: {\r\n");
      out.write("        \t\tdisplay: false,\r\n");
      out.write("        },\r\n");
      out.write("        scales: {\r\n");
      out.write("            xAxes: [{\r\n");
      out.write("            \t\tdisplay: false,\r\n");
      out.write("            }],\r\n");
      out.write("            yAxes: [{\r\n");
      out.write("            \t\tdisplay: false,\r\n");
      out.write("                ticks: {\r\n");
      out.write("                \tbeginAtZero: true,\r\n");
      out.write("              \t},\r\n");
      out.write("            }]\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("    plugins: [multiply1],\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("window.chart = new Chart(canvas1, config1);\r\n");
      out.write("      </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'IBMPlexSansKR-Text';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/IBMPlexSansKR-Text.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("        .public-footer{\r\n");
      out.write("        \ttop: 104em;\r\n");
      out.write("        \tposition: absolute;\r\n");
      out.write("            padding-top: 1.6em;\r\n");
      out.write("            padding-bottom: 1.6em;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            vertical-align: center;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            font-size: .86em;\r\n");
      out.write("            color: rgba(0, 0, 0, 0.7);\r\n");
      out.write("            box-shadow: 0.5rem 0.5rem 0.5rem #BCC6D2, \r\n");
      out.write("            -0.5rem -0.5rem 0.5rem rgba(244, 249, 255, 0.726);\r\n");
      out.write("        \tborder-radius: 3rem;\r\n");
      out.write("            background-color: rgb(204, 219, 238);\r\n");
      out.write("        }\r\n");
      out.write("        .footer-inner{\r\n");
      out.write("            width: 114em;\r\n");
      out.write("            height: 10em;\r\n");
      out.write("        }\r\n");
      out.write("        .logo-title{\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"public-footer\">\r\n");
      out.write("        <p class=logo-title>Cookingking </p>\r\n");
      out.write("            <div class=\"footer-inner\">\r\n");
      out.write("            <p class=\"first-line\">\r\n");
      out.write("                <strong>상호명</strong> \r\n");
      out.write("                    주식회사 Cookingking\r\n");
      out.write("                <strong>개인정보책임자</strong> \r\n");
      out.write("                    김동현\r\n");
      out.write("                <strong>사업자등록번호</strong> \r\n");
      out.write("                    111-11-11111\r\n");
      out.write("                <strong>통신판매신고번호</strong> \r\n");
      out.write("                    2020-서울강남-0825\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"second-line\">\r\n");
      out.write("                <strong>주소</strong> \r\n");
      out.write("                    서울특별시 강남구 테헤란로 10길 9 그랑프리빌딩 5F\r\n");
      out.write("                <strong>대표번호</strong> \r\n");
      out.write("                    0000-0000\r\n");
      out.write("                <strong>이메일</strong>\r\n");
      out.write("                    we_love_cookingking@ckk.com \r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"third-line\">\r\n");
      out.write("                <strong>(주)Cookingking</strong>\r\n");
      out.write("                    은 통신판매중개자이며 통신판매 당사자가 아닙니다. \r\n");
      out.write("                    따라서 클래스/개인간 거래 및 판매에 대하여 책임을 지지 않습니다.\r\n");
      out.write("            </p>        \r\n");
      out.write("            <p class=\"last-line\">\r\n");
      out.write("            <strong>Copyright © Cookingking. All Rights Reserved.</strong>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
